language: php
install: composer install
cache:
 directories:
   - vendor

php:
  - 5.5
  - 5.6

env:
  - DB=mysql

services:
  - memcached

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: DB=pgsql

    - php: 5.4
      env: DB=sqlite

    - php: 5.4
      env: PHPCS=1


before_script:
  - echo "Before Script"
  - composer show --installed
  - date
  - ./vendor/bin/phpcs --config-set installed_paths $(pwd)/vendor/cakephp/cakephp-codesniffer

script:
  - echo "Running test script"
  - date
  - env
  # - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./app"
  - ./vendor/bin/phpcs -p --extensions=php --standard=CakePHP ./app
  - ./vendor/bin/phpcbf -p --extension=php --standard=CakePHP ./app

notifications:
  email: le.hung@givery.co.jp